---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aljedkrq/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH/.env
    - cd $DEPLOYPATH
    - composer install --optimize-autoloader --no-dev
    - php artisan key:generate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan migrate --force
    - php artisan storage:link
    - npm install
    - npm run build
    - php artisan optimize
